add new description of the classes
new-hope/BlastingOffwithBootstrap pull request #2
Opened 2017-01-26 15:19 UTC by Grishchenko

2017-01-26 16:38 UTC, chilicoder commented on css/main.css
> +	color: #d8e6f3;
Я кстати для особого шику тут еще транзишн легкий добавляю. Анимированное изменение цвета чуть приятнее на глаз

2017-01-26 16:38 UTC, chilicoder commented on css/main.css
> +Он вместо одной строки подвала делает две и элементы подвала располагаются
Комменты лучше делать на одном языке. Советую английский для дополнительной тренировки. Кривой английский тоже сойдет. Русский только если совсем тяжело. Но тогда везде русский

2017-01-26 16:38 UTC, chilicoder commented on index.html
> -		<div class="navbar navbar-default navbar-static-top">
А почему дефалт класс удалил?

2017-01-26 18:52 UTC, Grishchenko commented on css/main.css
> +Он вместо одной строки подвала делает две и элементы подвала располагаются
понял. буду тренироваться. Переделать?

2017-01-26 19:04 UTC, Grishchenko commented on index.html
> -		<div class="navbar navbar-default navbar-static-top">
следую видео. сначала navbar-default заменил на navbar-inverse, потом просто для всего navbar задал цвет фона. Он получается там не нужен.

2017-01-26 19:04 UTC, Grishchenko commented on css/main.css
> +	color: #d8e6f3;
поясни про транзишн.

2017-01-28 06:57 UTC, chilicoder commented on css/main.css
> +Он вместо одной строки подвала делает две и элементы подвала располагаются
ага

2017-01-28 06:57 UTC, chilicoder commented on css/main.css
> +	color: #d8e6f3;
`transition: color 0.5s ease;`
в прошлом туториале у тебя похожее было

2017-01-28 09:05 UTC, Grishchenko commented on css/main.css
> +	color: #d8e6f3;
да, было. Вставить transition или так оставить?

2017-01-28 15:57 UTC, yarigpopov requested changes

2017-01-28 15:57 UTC, chilicoder commented on css/main.css
> +	color: #5396cf;
а давай сюда в качестве тренировки небольшой транзишн добавим.
задача такая, сделать переход цвета не внезапный, а постепенный.. допустим за 0.3 секунды ease-in
сможешь?

2017-01-28 15:57 UTC, chilicoder commented on blog.html
> +		<meta name="viewport" content="width-device-width, initial-scale=1">
<img width="1274" alt="screen shot 2017-01-28 at 16 55 34" src="https://cloud.githubusercontent.com/assets/3491833/22397826/bca35d68-e57a-11e6-9df5-5a5bc3c0f40b.png">
здесь чтото некорректно

2017-01-28 15:57 UTC, chilicoder commented
<img width="284" alt="screen shot 2017-01-28 at 16 51 40" src="https://cloud.githubusercontent.com/assets/3491833/22397828/cda28832-e57a-11e6-9c10-79741b483976.png">
а давай еще тут немного больше места между элементами

2017-01-29 14:24 UTC, Grishchenko commented on css/main.css
> +	color: #5396cf;
сделал

2017-01-29 14:27 UTC, Grishchenko commented
все вроде сделал. Я так понял надо было увеличить пространство между элементами по вертикали.

2017-01-29 15:30 UTC, yarigpopov requested changes

2017-01-29 15:30 UTC, chilicoder commented on blog.html
> +						<a class="transition" href="tickets.html">Book your ticket today</a></p>
А подумай, как добиться такого же результата не добавляя класс транзишн во все ссылки. Если за полчаса не догадаешься, спроси меня

2017-01-29 15:42 UTC, Grishchenko commented on blog.html
> +						<a class="transition" href="tickets.html">Book your ticket today</a></p>
Я так сделал, потому что мне кажется что удобнее классы разделять по функционалу, а по другому так
.footer a:hover {
	color: #d8e6f3;
	transition: 0.5s ease-in;
}

2017-01-29 17:02 UTC, yarigpopov requested changes

2017-01-29 17:02 UTC, chilicoder commented on index.html
> +							<li class="mb"><i class="glyphicon glyphicon-globe"></i>Orlando, FL</li>
а тут слабо одним классом обойтись, а не тремя? 
а еще нужно немного горизонтального воздуха добавить

2017-01-29 19:13 UTC, yarigpopov approved these changes

2017-01-29 19:13 UTC, chilicoder commented
Great work!

2017-01-29 19:13 UTC, merged